
LDFLAGS = -L/opt/owfs/lib -Wl,--rpath -Wl,/opt/owfs/lib -lownet
CFLAGS = -g -I/opt/owfs/include

OBJS = ownetexample.o

all:	ownetexample

ownetexample: $(OBJS)
	gcc $(CFLAGS) $(LDFLAGS) -o $@ $(OBJS)

%.o: %.c
	gcc $(CFLAGS) -c -o $@ $<

clean:
	$(RM) -f ownetexample *.o *~ .~
