<?php

/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.24
 * 
 * This file is not intended to be easily readable and contains a number of 
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG 
 * interface file instead. 
 * ----------------------------------------------------------------------------- */

$extensionFile = "/usr/lib/php4/20020429/php_OW.so";

//make sure that we are ABLE to load libraries
if( !(bool)ini_get( "enable_dl" ) || (bool)ini_get( "safe_mode" ) ) 
{

  die( "dh_local(): Loading extensions is not permitted.\n" );
}


//check to make sure the file exists
if( !file_exists( $extensionFile ) ) 
{
  die( "dl_local(): File '$extensionFile' does not exist.\n" );
}


//check the file permissions
if( !is_executable( $extensionFile ) ) 
{
  die( "dl_local(): File '$extensionFile' is not executable.\n" );
}


global $PHP_OW_LOADED__;
if ($PHP_OW_LOADED__) return;
$PHP_OW_LOADED__ = true;

/* if our extension has not been loaded, do what we can */
if (!extension_loaded("php_OW")) {
	if (!dl("php_OW.so")) return;
}



?>
