#! /bin/sh

# OSX uses BSD libtool by default -- we want GNU
case $(uname) in
	Darwin)
		LZ=glibtoolize ;;
	*)
		LZ=libtoolize ;;
esac

rm -rf *cache
$LZ -f -c -i && aclocal && autoheader && autoconf && automake -a -c --foreign && echo "Run './configure' and 'make' to build owfs"
