#! /bin/sh

# OSX uses BSD libtool by default -- we want GNU
case `uname` in 
	Darwin*) 
		LZ=libtoolize ;;
	*) 
		LZ=glibtoolize ;;
esac

rm -rf *cache
$(LZ) -f -c -i && aclocal -I src/scripts/m4 && autoheader && autoconf && automake -a -c --foreign && echo "Run './configure' and 'make' to build owfs"
