#! /bin/sh

# OSX uses BSD libtool by default -- we want GNU
ACLOCAL_EXTRA=""
case `uname` in 
	Darwin*) 
		LZ=glibtoolize
		ACLOCAL_EXTRA="-I /usr/local/share/aclocal/"
		;;
	*) 
		LZ=libtoolize ;;
esac

rm -rf *cache
$LZ -f -c -i && aclocal -I src/scripts/m4 $ACLOCAL_EXTRA && autoheader && autoconf && automake -a -c --foreign && echo "Run './configure' and 'make' to build owfs"
