#if 0
OWTCL_MAJOR_VERSION = 0 OWTCL_MINOR_VERSION = 2 OWTCL_VERSION = $(OWTCL_MAJOR_VERSION).$(OWTCL_MINOR_VERSION)
#endif
#define OWTCL_MAJOR_VERSION 0
#define OWTCL_MINOR_VERSION 2
#define OWTCL_VERSION "0.2"
