.\" Copyright (C) 2001 Real-Time Systems, Inc.
.\" See section COPYING for conditions for redistribution
.TH linksniff "1" "2007 April 10" "OWFS" "One-wire Filesystem"
.SH NAME
linksniff \- Interface to ibuttonlink 1-wire sniff mode
.SH SYNOPSIS
.B linksniff \fB-p\fR PORT [\fB-o\fR outputfile] [\fB--version\fR]
.SH DESCRIPTION
.PP
.\" Add any additional description here
.PP
\fBlinksniff\fR manages sniff mode of \fIiButtonlink's\fR \fBLINK\fR 1-wire adapter.
.PP
Normally the \fBLINK\fR functions as a 1-wire bus master, and can be
controlled by any number of 1-wire programs including \fBOWFS\FR and \fBxt\fR.
.PP
There is another mode where the \fBLINK\fR sits on a 1-wire network run by a different
bus master and reports the activity on the network. \fBlinksniff\fR is a simple program
to put the \fBLINK\fR in sniff mode and report the activity to the console and
optionally a logging file.

.PP
\fBlinksniff\fR performs some filtering on standard input:  ESC and EOF cause
\fBxt\fR to exit.
.PP
All characters received from the serial port are copied to standard output
unchanged.
.SH OPTIONS
The following arguments are required:
.TP
\fB\-p\fR PORT
Select serial port (of the \fBLINK\fR) to use.
.PP
The following options are accepted:
.TP
\fB\-o\fR outputfile
Log activity to this file as well as the console.
.TP
\fB\-\-version\fR
Output version information and exit.
.SH "REPORTING BUGS"
Report bugs to <paul.alfille@gmail.com>.
.SH HISTORY
\fBlinksniff\fR is derived from \fBxt\fR written by David Querbach.
(Which in turn was derived from \fBminiterm\fR).
It was customized by Paul Alfille to add an output file and to talk to the \fBLINK\fR.
.PP
Specific modifications include setting the initial serial port settings,
sending setup information, and setting the serial port to sniff speed.
.SH COPYRIGHT
Copyright \(co 2002 Real-Time Systems, Inc.
.br
GPL version 2
.br
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
