.\" Copyright (C) 2001 Real-Time Systems, Inc.
.\" See section COPYING for conditions for redistribution
.TH xt "1" "2002 September 9" "RTS" "Real-Time Systems Tools"
.SH NAME
xt \- simple terminal emulator with snooping capability
.SH SYNOPSIS
.B xt \fB-p\fR PORT [\fB-b\fR BAUDRATE] [\fB-s\fR STOPBITS] [\fB-t\fR TTYLINK] [\fB--version\fR]
.SH DESCRIPTION
.PP
.\" Add any additional description here
.PP
\fBxt\fR copies its standard input to PORT while simultaneously copying PORT
to its standard output.  In this way, \fBxt\fR provides a simple terminal
emulator.
.PP
\fBxt\fR performs some filtering on standard input:  ESC and EOF cause
\fBxt\fR to exit; \fB^B\fR causes \fBxt\fR to send a line break.  For
convenience in use with different keyboards, DEL is converted to BS, and  NL
is converted to CR.  All other characters are transmitted unchanged.
.PP
All characters received from the serial port are copied to standard output
unchanged.
.PP
If a TTYLINK is specified, \fBxt\fR allocates a pseudo-tty and creates a
symbolic link TTYLINK pointing to it.  \fBxt\fR then copies
TTYLINK to PORT and PORT to TTYLINK in addition to the standard copying
described above.
.PP
\fBxt\fR performs no modification of the data passing between TTYLINK and
PORT.
.PP
Since TTYLINK appears to be a tty for most purposes, another program such as
a debugger can communicate via TTYLINK with a target device attached to
PORT.  The user of \fBxt\fR can then monitor the PORT-to-TTYLINK
communication on \fBxt\fR's standard output, while continuing to send data
from \fBxt\fR's standard input to PORT, if desired.
.PP
The following arguments are required:
.TP
\fB\-p\fR PORT
Select serial port to use.
.PP
The following options are accepted:
.TP
\fB\-b\fR BAUDRATE
Select baud rate to use (default 9600).  Supported baud rates vary with the
host operating system, but usually include 0, 50, 75, 110, 134, 150, 200,
300, 600, 1200, 1800, 2400, 4800, 9600, 19200, 38400, 57600 and 115200.
.TP
\fB\-s\fR STOPBITS
Set number of stop bits, either 1 or 2 (default 1).
.TP
\fB\-t\fR TTYLINK
Allocate a pseudo-tty, and create a symbolic link TTYLINK pointing to it.
.TP
\fB\-\-version\fR
Output version information and exit.
.SH "REPORTING BUGS"
Report bugs to <querbach@realtime.bc.ca>.
.SH COPYRIGHT
Copyright \(co 2002 Real-Time Systems, Inc.
.br
GPL version 2
.br
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
