'\"
'\" Copyright (c) 2003-2004 Paul H Alfille, MD
'\" (palfille@earthlink.net)
'\"
'\" Device manual page for the OWFS -- 1-wire filesystem package
'\" Based on Dallas Semiconductor, Inc's datasheets, and trial and error.
'\"
'\" Free for all use. No waranty. None. Use at your own risk.
'\" $Id$
'\"
.TH DS2450 3  2003 "OWFS Manpage" "One-Wire File System"
.SH NAME
.B DS2450
- Quad A/D Converter
.SH SYNOPSIS
Voltage * 4  and Memory.
.HP
.B 20
[.]XXXXXXXXXXXX[XX][/[
.B memory
|
.B pages/page.[0-3|ALL]
|
.B PIO.[A-D|ALL]
|
.B power
|
.B volt.[A-D|ALL]
|
.B volt2.[A-D|ALL]
|
.B address
|
.B crc8
|
.B id
|
.B present
|
.B type
]]
.SH FAMILY CODE
.TP
20
.SH SPECIAL PROPERTIES
.SS memory
.I read-write, binary
.br
32 bytes of data. Much has special implications. See the datasheet.
.SS pages/page.0 ... pages/page.3 pages/page.ALL
.I read-write, binary
.br
Memory is split into 4 pages of 8 bytes each. Mostly for reading and setting device properties. See the datasheet for details.
.br
.I ALL
is an aggregate of the pages. Each page is accessed sequentially.
.SS PIO.A ... PIO.D PIO.ALL
.I read-write, yes-no
.br
Pins used for digital control. 1 turns the switch on (conducting). 0 turns the switch off (non-conducting).
.br
Control is specifically enabled. Reading
.I volt
will turn off this control.
.br
.I ALL
is an aggregate of the voltages. Readings are made separately.
.SS power
.I read-write, yes-no
.br
Is the
.I DS2450
externally powered? (As opposed to parasitically powered from the data line).
.br
The analog A/D  will be kept on continuously. And the bus will be released during a conversion allowing other devices to communicate.
.br
Set true (1) only if Vcc powered (not parasitically powered). Unfortunately, the
.I DS2450
cannot sense it's powered state. This flag must be explicitly written, and thus is a potential source of error if incorrectly set.
.br
It is always safe to leave
.I power
set to the default 0 (off) state.
.SS volt.A ... volt.D volt.ALL
.I read-only, floating point
.br
Voltage read, 16 bit resolution. Range 0 - 5.10V.
.br
Output (
.I PIO
) is specifically disabled.
.br
.I ALL
is an aggregate of the voltages. Readings are made separately.
.SS volt2.A ... volt2.D volt2.ALL
.I read-only, floating point
.br
Voltage read, 16 bit resolution. Range 0 - 2.55V.
.br
Output (
.I PIO
) is specifically disabled.
.br
.I ALL
is an aggregate of the voltages. Readings are made separately.
.SH STANDARD PROPERTIES
.SS address
.I read-only, ascii
.br
The 48-bit middle portion of the unique ID number. Does not include the family code or CRC. Given as upper case hexidecimal digits (0-9A-F).
.SS crc8
.I read-only, ascii
.br
The 8-bit error correction portion. Uses cyclic redundancy check. Computed from the preceeding 56 bits of the unique ID number. Given as upper case hexidecimal digits (0-9A-F).
.SS family
.I read-only, ascii
.br
The 8-bit family code. Unique to each
.I type
of device. Given as upper case hexidecimal digits (0-9A-F).
.SS id
.I read-only, ascii
.br
The entire 64-bit unique ID. Given as upper case hexidecimal digits (0-9A-F).
.SS present
.I read-only, yes-no
.br
Is the device currently
.I present
on the 1-wire bus?
.SS type
.I read-only, ascii
.br
Part name assigned by Dallas Semi. E.g.
.I DS2401
Alternative packaging (iButton vs chip) will not be distiguished.
.SH ALARMS
None.
.SH DESCRIPTION
This is a 1-wire bus device. The 1-wire bus is a simple networking system created by Dalla Semiconductor that allows low-cost low-power communication over a single wire (plus ground). Power is often delivered "parasitically" from the same data line. Each device has a unique unalterable ID and can be individually addressed.
.PP
The
.B DS2450
is a high resolution A/D converter with 4 channels. Lower resolution voltage sensing (but with temperature) can be obtained with the
.B DS2436
and
.B DS2438
.SH ADDRESSING
All 1-wire devices are factory assigned a unique 64-bit address. This address is of the form:
.TP
.B Family Code
8 bits
.TP
.B Address
48 bits
.TP
.B CRC
8 bits
.IP
.PP
Addressing under OWFS is in hexidecimal, of form:
.IP
.B 01.123456789ABC
.PP
where
.B 01
is an example 8-bit family code, and
.B 12345678ABC
is an example 48 bit address.
.PP
The dot is optional, and the CRC code can included. If included, it must be correct.
.SH DATASHEET
.br
http://pdfserv.maxim-ic.com/en/ds/DS2450.pdf
.SH FILES
.TP
libow.so
Library providing most of the OWFS system. Bus master control, data parsing, etc.
.TP
owfs
Filesystem implementation. User space, using the FUSE kernel module.
.TP
owhttpd
Web server implementation of the OWFS system.
.SH SEE ALSO
.so seealso
.SH AVAILABILITY
http://owfs.sourceforge.net
.SH AUTHOR
Paul Alfille (palfille@earthlink.net)
