'\"
'\" Copyright (c) 2003-2004 Paul H Alfille, MD
'\" (paul.alfille@gmail.com)
'\"
'\" Device manual page for the OWFS -- 1-wire filesystem package
'\" Based on Dallas Semiconductor, Inc's datasheets, and trial and error.
'\"
'\" Free for all use. No waranty. None. Use at your own risk.
'\" $Id$
'\"
.TH HobbyBoards_EE/EF 3  2009 "OWFS Manpage" "One-Wire File System"
.SH NAME
.TP 
EEEF
HobbyBoards EE/EF Microprocessor-based slaves
.TP
UVI
Ultra Violet (UV) Index sensor
.TP
Moisture
Soil and Leaf moisture measurements
.SH SYNOPSIS
General EE device
.br
.B EE
[.]XXXXXXXXXXXX[XX][/[
.B temperature
|
.B version
|
.B type_number
|
.B temperature_offset
|
.so standard_mini.3so
]]
.PP
UVI sensor
.br
.B EE
[.]XXXXXXXXXXXX[XX][/[
.B UVI/UVI
|
.B UVI/UVI_offset
|
.B UVI/in_case
|
.B UVI/valid
|
.B temperature
|
.B version
|
.B type_number
|
.B temperature_offset
]]
.PP
General EF device
.br
.B EF
[.]XXXXXXXXXXXX[XX][/[
.B version
|
.B type_number
|
.so standard_mini.3so
]]
.PP
Moisture Meter
.br
.B moisture/sensor.[0-3|ALL]
.br
.B moisture/is_moisture.[0-3|ALL|BYTE]
|
.B moisture/is_leaf.[0-3|ALL|BYTE]
.br
.B moisture/calibrate/min
|
.B moisture/calibrate/max
|
.B moisture/calibrate/raw.[0-4|ALL]
.SH FAMILY CODE
.TP
.I EE
Device with temperature
.TP
.I EE
UVI
.TP
.I EF
Device without temperature
.TP
.I EF
Moisture Meter
.SH TEMPERATURE PROPERTIES
.SS temperature
.I read-only, floating point
.br
Temperature read every 30 seconds. Resolution .5C (uses an on-board DS18B20). Temperature is only present in the EE-series devices.
.SS temperature_offset
.I read-write, floating point
.br
Offset stored on device to apply to temperature readings.
.SH UVI PROPERTIES
.SS UVI/UVI
.I read-only floating point
.br
UV Index (ultraviolet index) in the range 0.0 to 16.0 resolution .1
.PP
Only the UVI version of the EE device has a UVI sensor. Readings made every .5 seconds.
.SS UVI/UVI_offset
.I read-write, floating point
.br
Signed offset to apply to the UVI measurement. Stored on-device non-volatile.
.SS UVI/in_case
.I read-write, yes-no
.br
Flag to apply compensation for the protective case. Stored on-device non-volatile.
.SS UVI/valid
.I read-only, yes-no
Flag the the EE device type matches the known UVI type.
.SH Moisture Meter
.SS moisture/sensor.0 .. moisture/sensor.3 moisture/sensor.ALL
.I read-only integer
.br
Up to 4 sensors reading moisture can be attached. 
.I OWFS
addresses the sensors as 0 through 3 while the datasheet uses 1-4.
Two types of external sensors are supported (and the data range):
.TP
Watermark Soil Moisture Sensor
0-199
.TP
Leaf Wetness Sensor
0-99
.SS moisture/is_moisture.0 .. moisture/is_moisture.3 moisture/is_moisture.ALL
.SS moisture/is_leaf.0 .. moisture/is_leaf.3 moisture/is_leaf.ALL
.I read-write yes_no
.br
Set or get the type of sensor attached to each channel. Note that 
.I OWFS
addresses the sensors as 0 through 3 while the datasheet uses 1-4.
Two types of external sensors are supported:
.TP
Watermark Soil Moisture
Sensor
.TP
Leaf Wetness
Sensor
.P
Note that
.I is_leaf
and 
.I is_moisture
are complementary and clearing one sets the other.

.SS moisture/calibrate/min
.SS moisture/calibrate/max
.I read-write unsigned integer
.br
Set or get the upper and lower range for the raw data for leaf wetness scaling. See the datasheet for details.

.SS moisture/calibrate/raw.0 .. moisture/calibrate/raw.3 moisture/calibrate/raw.ALL
.I read-only unsigned integer
.br
Read the raw leaf wetness values for setting scaling. See the datasheet for details.
Note that 
.I OWFS
addresses the sensors as 0 through 3 while the datasheet uses 1-4.
.SH IDENTIFICATION PROPERTIES
.SS version
.I read-only, ascii
.br
Firmware version for the EE/EF device. Reported in HH.HH format where HH is a hex digit (0-9A-F).
.SS type_number
.I read-only, integer
.br
Index of the type of sensor built into this device. Current known assignments:
.TP
1
UVI (Ultraviolet index)
.TP
2
Moisture meter
.TP
3
Moisture meter with datalogger
.TP
4
Sniffer
.TP
5
Hub
.SH STANDARD PROPERTIES
.so standard.3so
.SH ALARMS
None
.SH DESCRIPTION
.so description.3so
.SS EE / EF
The
.B EEEF (3)
are a reference platform of microprocessor based 1-wire slaves. In general they require external power, and have an on-board index for the specific capabilities. They are designed by Eric Vickery at HobbyBoards.com
.PP
The
.I EE
class device uses family code EE and has an included temperature sensor. The
.I EF
devices have no temperature sensor,
.SS UVI
The
.I UVI
sensor is an implementation of the
.I EE
class device with Ultra Violet Index sensing. All it's specific properties are in the
.I UVI/
directory.
.SH ADDRESSING
.so addressing.3so
.SH DATASHEET
.br
http://www.hobby-boards.com/catalog/links/uvi2-r1/UVI%20Meter%20User%20Manual.pdf
.br
http://www.hobby-boards.com/download/manuals/Moisture%20Meter.pdf
.SH SEE ALSO
.so seealso.3so
.SH AVAILABILITY
http://www.owfs.org
.SH AUTHOR
Paul Alfille (paul.alfille@gmail.com)
