#!/bin/sh
for s in 1 3 ; do
    for x in `ls *.$s` ; do
	rman -f HTML $x > ../../../ow-website/`basename $x .$s`.html; 
	perl -i -p -e 's#(<body.*?>)#$1<\!--\#include virtual=\"/head\.ssi\" -->#' ../../../ow-website/`basename $x .$s`.html; 
	perl -i -p -e 's#</body>#<\!--\#include virtual=\"/foot\.ssi\" --><address>\&copy\; 2003 Paul H\. Alfille and The owfs Team</address>
	<address>\$Id\$</address></body>#' ../../../ow-website/`basename $x .$s`.html; 
    done ; 
done
