#!/bin/sh
for x in *.[1-8n] ; do
    echo $x
    rman -f HTML $x | /usr/bin/tail -n+4 > html/$x

#    perl -i -p -e 's#(\.[1-9n])\b#$1.html#g' ../../../ow-website/$x.html; 
#    perl -i -p -e 's#(<body.*?>)#$1<\!--\#include virtual=\"/head\.ssi\" -->#' ../../../ow-website/$x.html; 
#    perl -i -p -e 's#</body>#<\!--\#include virtual=\"/foot\.ssi\" --><address>\&copy\; 2003-4 Paul H\. Alfille and The owfs Team</address><address>\$Id\$</address></body>#' ../../../ow-website/$x.html; 
done

scp html/* owfs@owfs.org:public_html/uploads
