.TH OWHTTPD 8
.SH OWHTTPD
owfs \- 1-wire filesystem.
.SH SYNOPSIS
.B owfs
.I "-h  -p -d -t mountpoint"
.SH "DESCRIPTION"
.B owfs
is a user-space filesystem that shows the Dallas/Maxim 1-Wire bus attached to a serial port. The main directory shows the devices found, You can then navigate to individual devices, and view/alter their properties.
.TP
There is optional data caching. Which can speed repeated access to the same 1wire properties (but is potentially confusing). Use the uncached directory to see immediate values.
.TP
The underlying interface to the 1-wire bus is identical to OWHTTPD -- the 1-wire web server. Only the top layer has been modified to serve files instead of web pages. Development here, and support for new devices, will progress with that project.
.TP
The 1-wire file system is a modified version of fuse examples by Miklos Szeredi. It is now single-threaded, and serves no files. Security should therefore be good. Only the 1-wire bus is at risk. The fuse library and kernel module is needed. (See http://www.sourceforge.net/projects/avf).

.SH OPTIONS
.TP
.B \-h
Show summary of options.
.TP
.B \-d device
Set the serial port to monitor. It should have a LINK or DS9097U attached. The "-d" is optional if two arguments are supplied. (See examples).
.TP
.B \-t seconds
Set the number of seconds that volitile data (measured values like temperature and voltage) should be cached before requerying the BUS. More stable values will be saved ten times longer (switch settings, memory contents).

.SH EXAMPLE
owfs -d /dev/ttyS0 /mnt/1wire
.TP
owfs /dev/ttyS0 /mnt/1wire

.SH NOTES
See http://owfs.sourceforge.net for the current version.

.SH AUTHOR
Paul Alfille (palfille@earthlink.net)
