'\"
'\" Copyright (c) 2003-2004 Paul H Alfille, MD
'\" (palfille@earthlink.net)
'\"
'\" Program manual page for the OWFS -- 1-wire filesystem package
'\" Based on Dallas Semiconductor, Inc's datasheets, and trial and error.
'\"
'\" Free for all use. No waranty. None. Use at your own risk.
'\" $Id$
'\"
.TH OWFS 1 2004 "OWFS Manpage" "One-Wire File System"
.SH NAME
.B owfs
\- 1-wire filesystem
.SH SYNOPSIS
.B owfs
.so cmdline_mini
[host:]port
.I mountdir
.br
.B owfs
.so cmdline_mini
[host:]port
.B --mountpoint
mountdir
.br
.B owfs
.so cmdline2_mini
[
.I \-\-fuse_opt
options ]
.I mountpoint
[
.I \-\-allow_other
]
.br
.B owfs
.I \-V \-\-version
.br
.B owfs
.I \-h | \-\-help
[=
.I device
|
.I program
|
.I job
|
.I cache
|
.I temperature
]

.SH "DESCRIPTION"
.so description
.SS owfs
.B owfs (1)
is the filesystem client of the 
.I OWFS
family of programs. It is Linux-specific, and requires the 
.I fuse
kernel module and library. (http://fuse.sourceforge.net) which is a user-mode filesystem driver.
.PP
Essentially, the entire 1-wire bus is mounted to a place in your filesystem. All the 1-wire devices are accessible using standard file operations (read, write, directory listing). The system is safe, no actual files are exposed, these files are virtual. Not all operations are supported. Specifically, file creation, deletion, linking and renaming are not allowed. (You can link from outside to a owfs file, but not the other way around).
.so cmdline
.SH SPECIFIC OPTIONS
.SS \-\-mountpoint
directory to mount the 1-wire file system
.SS \-\-allow_other
Shorthand for fuse mount option "-o allow_other"  Allows uther users to see the fuse (owfs) mount point and file system. Requires a setting in /etc/fuse.conf as well.
.SS \-\-fuse-opt "options"
Sends options to the fuse-mount process. Options should be quoted, e.g. "\"-o allow_other\"" .
.SH EXAMPLE
.TP
owfs -d /dev/ttyS0 /mnt/1wire
Adapter on serial port
.TP
owfs -F -u /mnt/1wire
USB adapter, temperatures reported in Fahrenheit
.TP
owfs -s 10.0.1.2:3001 /mnt/1wire
Connect to a OWFS server process (
.I owserver
) that was started on another machine at tcp port 3001
.SH SEE ALSO
.so seealso
.SH AVAILABILITY
http://www.owfs.org
.SH AUTHOR
Paul Alfille (palfille@earthlink.net)
