'\"
'\" Copyright (c) 2003-2004 Paul H Alfille, MD
'\" (palfille@earthlink.net)
'\"
'\" Device manual page for the OWFS -- 1-wire filesystem package
'\" Based on Dallas Semiconductor, Inc's datasheets, and trial and error.
'\"
'\" Free for all use. No waranty. None. Use at your own risk.
'\" $Id$
'\"
.TH OWHTTPD 1 2004 "OWFS Manpage" "One-Wire File System"
.SH NAME
.B owhttpd
\- Tiny webserver for 1-wire control
.SH SYNOPSIS
.B owhttpd
.so cmdline_mini
.I \-p
tcp-port
.br
.B owhttpd
.so cmdline2_mini
.I \-p
[host:]tcp-port
.br
.B owhttpd
.I \-h \-\-help
[=
.I device
|
.I program
|
.I job
|
.I cache
|
.I temperature
]
.br
.B owhttpd
.I \-V \-\-version
.SH "DESCRIPTION"
.so description
.SS owhttpd
.B owhttpd (1)
is a small webserver that shows the Dallas/Maxim 1-Wire bus attached to a serial port. The main view shows the devices found, You can then navigate to individual devices, and view/alter their properties.
.PP
.B owhttpd (1)
uses the same naming convention as
.B owfs (1)
, where the URL corresponds to the filename.
.PP
The web server is a modified version of chttpd by Greg Olszewski. It serves no files from the disk, only virtual files from the 1-wire bus. Security should therefore be good. Only the 1-wire bus is at risk.
.SH SPECIFIC OPTIONS
.SS \-p portnum
Sets the tcp port the web server runs on. Access with the URL http://servernameoripaddress:portnum
.so cmdline
.so timeout
.SH EXAMPLE
.TP
owhttpd -p 3001 -d /dev/ttyS0
Web server runs on tcp port 3001, serial adapter at ttyS0
.TP
owhttpd -p 3001 -s littlehost:3001 --error_level=3
Web server on port 3001, from
.I owserver
process on host "littlehost", extensive error messages.
.TP
owhttpd -p 3001 -u -u2 -r
Read-only web server on port 3001, using two usb adapters.
.SH AVAILABILITY
http://www.owfs.org
.SH SEE ALSO
.so seealso

.SH AUTHOR
Paul Alfille (palfille@earthlink.net)
