'\"
'\" Copyright (c) 2003-2004 Paul H Alfille, MD
'\" (palfille@earthlink.net)
'\"
'\" Device manual page for the OWFS -- 1-wire filesystem package
'\" Based on Dallas Semiconductor, Inc's datasheets, and trial and error.
'\"
'\" Free for all use. No waranty. None. Use at your own risk.
'\" $Id$
'\"
.TH OWSERVER 1 2004 "OWSERVER Manpage" "One-Wire File System"
.SH NAME
.B owserver
\- Backend server (daemon) for 1-wire control
.SH SYNOPSIS
.B owserver
[
.B \-r \-\-readonly
|
.B \-w \-\-write
] [
.B \-t
timeout ] [
.B \-\-background
|
.B \-\-foreground
]
.B \-p
tcp-port
.B \-d
serialport |
.B \-u
|
.B \-s
tcp-port
.br
.B owserver
.B \-h
.br
.B owserver
.B \-V \-\-version
.SH "DESCRIPTION"
.B owserver
is the backend component of the OWFS 1-wire bus control system.
.I owserver
arbitrates access to the bus from multiple client processes. The physical bus is usually connected to a serial or USB port, and other processes connect to
.I owserver
over network sockets (tcp port). Communication can be local or over a network. Secure tunneling can be implemented using standard techniques.
.PP
Frontend clients include a filesystem representation:
.I owfs(1)
, and a webserver:
.I owhttpd(1).
Direct language bindings are also available, e.g:
.I owperl(1).
Several instances of each client can be initiated.
.PP
Each client can also connect directly to the physical bus, skipping
.I owserver
but only one client can connect to the physical bus safely. Simultaneous access is prevented by the operating system for USB ports, but unfortunately not serial ports. The safe way to share access to the 1-wire bus is via
.I owserver
with the clients connecting. Note:
.I owserver
can connect to another
.I owserver
process, though the utility of this technique is limited (perhaps as a
.I readonly
buffer?)
.PP
.I owserver
is by default multithreaded. Optional data caching is in the server, not clients, so all the clients gain efficiency.
.PP
The 1-wire protocol is a simple networking system and assiciated devices developed by Dallas Semiconductor (now Maxim). Communication is over a single line, with both power and data being supplied. Each 1-wire device has a unique address, hardwired during manufacture. Devices can be individually discovered and addressed. 1-wire devices include simple IDs, memory, temperature, pressure, voltage, humidity, clock, switches, encryption and more.
.SH OPTIONS
.SS \-\-background | \-\-foreground
Whether the program releases the console and enters daemon mode after evaluating command line options.
.I background
is the default.
.SS \-d \-\-device "deviceport"
Sets the serial port. It should have a LINK, DS9097U or DS9097 (passive adapter) attached. The "-d" is implied if two arguments are supplied. (See examples).
.br
Note: multiple instances of 
.I -d, -u, -s
are allowed. Each corresponds to a different 1-wire bus. The result will reflect the logical union of those buses.
.SS \-h \-\-help
Shows this summary of options.
.SS \-p portnum
Sets the tcp port that
.I owserver
runs on. Clients access this port with the \"-s\" command line option.
.br
Note: multiple instances of 
.I -p
are allowed. Each port will be treated identically.
.SS \-r \-\-readonly | \-w \-\-write
Set the read / write permissions on the 1-wire bus. Clients can also be started in read-only mode, which will restrict THAT client, even if
.I owserver
permits writing.
.br
Note that
.I readonly
mode does not prevent all 1-wire bus changes. On some 1-wire devices, reading will clear counters, clear alarms, or implicitly change resolution.
.SS \-s portnum | host:portnum
Connect to another
.I owserver
and not the physical 1-wire bus. Format port number, service name, (or host:port for a remote target).
.br
Note: multiple instances of 
.I -d, -u, -s
are allowed. Each corresponds to a different 1-wire bus. The result will reflect the logical union of those buses.
.SS \-t \-\-timeout "seconds"
Set the number of seconds that volitile data (measured values like temperature and voltage) should be cached before requerying the BUS. More stable values will be saved ten times longer (switch settings, memory contents). 10 seconds is the default. May be subsequently changed through client interface to the /settings/cache entries.
.SS \-u \-\-usb
Use the USB adapter (DS9490) as 1-wire bus master. An optional number 1,2,... specifies which adapter to use if more than one is present.
.br
Note: multiple instances of 
.I -d, -u, -s
are allowed. Each corresponds to a different 1-wire bus. The result will reflect the logical union of those buses.
.SS \-V \-\-version
.I Version
of this program and related libraries.
.SH EXAMPLE
.B owserver -p 3001 -d /dev/ttyS0
runs owserver on tcp port 3001 and connects to a physical 1-wire bus on a serial port.
.SH NOTES
See http://owfs.sourceforge.net for the current version.

.SH AUTHOR
Paul Alfille (palfille@earthlink.net)
