
LDFLAGS = -L/opt/owfs/lib -Wl,--rpath -Wl,/opt/owfs/lib -lowcapi
CFLAGS = -g -I/opt/owfs/include

OBJS = owcapiexample.o

all:	owcapiexample

owcapiexample: $(OBJS)
	gcc $(CFLAGS) $(LDFLAGS) -o $@ $(OBJS)

%.o: %.c
	gcc $(CFLAGS) -c -o $@ $<

clean:
	$(RM) -f owcapiexample *.o *~ .~
