#!/bin/bash

GROUP=owfs

if [ "$ACTION" = "add" ] && [ -f "$DEVICE" ]
then
    # check if $GROUP really exists
    if getent group $GROUP > /dev/null; then
	    chmod 660 "$DEVICE"
    	chown root.$GROUP "$DEVICE"
    fi
fi
