#if 0
OWTCL_MAJOR_VERSION = 1
OWTCL_MINOR_VERSION = 0
OWTCL_VERSION = $(OWTCL_MAJOR_VERSION).$(OWTCL_MINOR_VERSION)
#endif
#define OWTCL_MAJOR_VERSION 1
#define OWTCL_MINOR_VERSION 0
#define OWTCL_VERSION "1.0"
