name: build

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, ubuntu-20.04]
    steps:
    - uses: actions/checkout@v2
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
          php-version: "7.4"
    - name: install dependencies on Linux
      run: sudo apt-get update && sudo apt-get install -y libfuse-dev swig uthash-dev tcl-dev python3-dev libftdi1-dev libavahi-client-dev check
    - name: bootstrap
      run: ./bootstrap
    - name: configure
      run: ./configure
    - name: make
      run: make
    - name: check
      run: make check

  build-mac:
    runs-on: macos-12
    steps:
    - uses: actions/checkout@v2
    - name: install dependendencies on macOS
      run: brew install autoconf automake libtool pkg-config swig libftdi check && python3 -m pip install setuptools
    - name: bootstrap
      run: ./bootstrap
    - name: configure
      run: ./configure --disable-owphp --without-php
    - name: make
      run: make
    - name: check
      run: make check

  dist:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: bootstrap
      run: ./bootstrap
    - name: configure
      run: ./configure
    - name: make dist (.tar.gz)
      run: make dist-gzip
    - uses: actions/upload-artifact@v2
      with:
        name: source-dist
        path: owfs-*.*p*.tar.gz

  build-from-dist:
    needs: dist
    runs-on: ubuntu-latest
    steps:
    # FIXME: reusing steps from "jobs.build".
    # Verify if this is possible without copying verbatim.
    # Natural solution would be YAML anchors and pointers, but these
    # are not supported yet.
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
          php-version: "7.4"
    - name: install dependencies on Linux
      if: runner.os == 'Linux'
      run: sudo apt-get update && sudo apt-get install -y libfuse-dev swig uthash-dev tcl-dev python3-dev libftdi1-dev libavahi-client-dev check
    - uses: actions/download-artifact@v2
      with:
        name: source-dist
    - name: extract sources
      run: tar -x -f owfs-*.tar.gz --strip-components 1
    - name: configure
      run: ./configure
    - name: make
      run: make
