name: build

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, ubuntu-18.04, macos-10.15]
    steps:
    - uses: actions/checkout@v2
    - name: install dependencies on Linux
      if: runner.os == 'Linux'
      run: sudo apt-get install swig3.0 uthash-dev tcl-dev check
    - name: install dependendencies on macOS
      if: runner.os == 'macOs'
      run: brew install autoconf automake libtool pkg-config swig php check
    - name: bootstrap
      run: ./bootstrap
    - name: configure
      run: ./configure
    - name: make
      run: make
    - name: check
      run: make check
